// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebSecApp.Models;

namespace WebSecApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.6.20312.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebSecApp.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ProdCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebSecApp.Models.SecService", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("finishdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("prodcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("projduration")
                        .HasColumnType("int");

                    b.Property<string>("projecttype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("servName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("startdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("technology")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("SecSer");

                    b.HasData(
                        new
                        {
                            id = 1,
                            finishdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            prodcode = "CTXSF1",
                            projduration = 10,
                            projecttype = "Fixed",
                            servName = "WAF Design",
                            startdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            technology = "Citrix"
                        },
                        new
                        {
                            id = 2,
                            finishdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            prodcode = "CTXSF2",
                            projduration = 20,
                            projecttype = "Fixed",
                            servName = "WAF Build ",
                            startdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            technology = "Citrix"
                        },
                        new
                        {
                            id = 3,
                            finishdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            prodcode = "CTXST3",
                            projduration = 5,
                            projecttype = "T&M",
                            servName = "WAF Testing ",
                            startdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            technology = "Citrix"
                        },
                        new
                        {
                            id = 4,
                            finishdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            prodcode = "CTXST4",
                            projduration = 15,
                            projecttype = "T&M",
                            servName = "WAF Prod Deploy",
                            startdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            technology = "Citrix"
                        },
                        new
                        {
                            id = 5,
                            finishdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            prodcode = "AZSF1",
                            projduration = 20,
                            projecttype = "Fixed",
                            servName = "Azure Firewall ",
                            startdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            technology = "Microsoft"
                        },
                        new
                        {
                            id = 6,
                            finishdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            prodcode = "AZSF2",
                            projduration = 25,
                            projecttype = "Fixed",
                            servName = "Azure Sentinel",
                            startdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            technology = "Microsoft"
                        },
                        new
                        {
                            id = 8,
                            finishdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            prodcode = "AZSF3",
                            projduration = 30,
                            projecttype = "Fixed",
                            servName = "Azure Security Centre",
                            startdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            technology = "Microsoft"
                        },
                        new
                        {
                            id = 9,
                            finishdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            prodcode = "AZST4",
                            projduration = 15,
                            projecttype = "T&M",
                            servName = "Citrix ADC WAF on Azure ",
                            startdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            technology = "Microsoft"
                        },
                        new
                        {
                            id = 10,
                            finishdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            prodcode = "AZST4",
                            projduration = 15,
                            projecttype = "T&M",
                            servName = "Azure Endpoint Protection",
                            startdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            technology = "Microsoft"
                        },
                        new
                        {
                            id = 11,
                            finishdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            prodcode = "CTXSF5",
                            projduration = 15,
                            projecttype = "Citrix",
                            servName = "Citrix ADC Adnvanced WAF",
                            startdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            technology = "Microsoft"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
